-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.questions
    ADD COLUMN survey_id bigint NOT NULL;
ALTER TABLE IF EXISTS public.questions
    ADD CONSTRAINT questions_survey_id_fkey FOREIGN KEY (survey_id)
    REFERENCES public.surveys (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.answers
    ADD COLUMN question_id bigint NOT NULL;
ALTER TABLE IF EXISTS public.answers
    ADD CONSTRAINT answers_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE IF EXISTS public.text_answers
    ADD COLUMN question_id bigint NOT NULL;
ALTER TABLE IF EXISTS public.text_answers
    ADD CONSTRAINT text_answers_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
