-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.questions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone DEFAULT now(),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    is_contextual boolean NOT NULL DEFAULT false,
    context character varying COLLATE pg_catalog."default",
    total_answers bigint NOT NULL DEFAULT '0'::bigint,
    correct_answers bigint NOT NULL DEFAULT '0'::bigint,
    CONSTRAINT questions_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.questions
    OWNER to postgres;

GRANT ALL ON TABLE public.questions TO anon;

GRANT ALL ON TABLE public.questions TO authenticated;

GRANT ALL ON TABLE public.questions TO postgres;

GRANT ALL ON TABLE public.questions TO service_role;
